# @file GetTransform.srv
# @brief Custom service to send a transform matrix between
#        ROS nodes.
# @package slamon
# @project SLAMON
#
# @author
#   Bo Miquel Nordfeldt-Fiol (2024–2025)
#
# @license BSD-4-Clause
#   This file is part of the SLAMON project and is released under
#   the BSD 4-Clause License. See the LICENSE file for details.


# Request
time timestamp
---
# Response
geometry_msgs/TransformStamped tf